// src/constants.ts
//
// Single source of truth for every magic value used across the CLI.
// Nothing is hardcoded elsewhere — import from here.

// ─── Stellar network defaults ─────────────────────────────────────────────────

export const DEFAULT_RPC_URL = 'https://soroban-testnet.stellar.org';
export const DEFAULT_NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';

// ─── Network detection ────────────────────────────────────────────────────────

/** Fragment found in the mainnet network passphrase */
export const MAINNET_PASSPHRASE_FRAGMENT = 'Public Global';

/** Fragment found in the testnet network passphrase */
export const TESTNET_PASSPHRASE_FRAGMENT = 'Test SDF';

// ─── Explorer ─────────────────────────────────────────────────────────────────

export const EXPLORER_BASE_URL = 'https://stellar.expert/explorer';

// ─── Internal MCP tools ───────────────────────────────────────────────────────
//
// These are implementation-level plumbing tools generated by the MCP server.
// They are hidden from user-facing tool pickers to keep the UX clean.

export const INTERNAL_TOOLS = new Set([
  'sign-and-submit',
  'prepare-transaction',
  'prepare-sign-and-submit',
]);

// ─── Spinner copy ─────────────────────────────────────────────────────────────

export const SPINNER_CONNECTING = 'Connecting to MCP server…';
export const SPINNER_CALLING = (tool: string): string => `Calling ${tool}…`;
export const SPINNER_SIGNING = 'Signing & submitting…';

// ─── Exit codes ───────────────────────────────────────────────────────────────

export const EXIT_OK = 0;
export const EXIT_ERROR = 1;
