/**
 * generate-types — CLI for @stellar-mcp/client
 *
 * Connects to a running MCP server, calls listTools(), converts each tool's
 * JSON Schema input to TypeScript interfaces, and writes a typed file with a
 * `createMCPClient` factory. Users import that factory instead of MCPClient
 * directly — no generics, no magic strings.
 *
 * Usage:
 *   npx mcp-generate-types --url http://localhost:3001/mcp [--out ./mcp-types.ts]
 */

import { parseArgs } from 'node:util';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { compile } from 'json-schema-to-typescript';
import { createTransport, createSSETransport } from '../transport.js';

// ─── CLI Args ─────────────────────────────────────────────────────────────────

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    url: { type: 'string' },
    out: { type: 'string', default: 'mcp-types.ts' },
    help: { type: 'boolean', default: false },
  },
  strict: true,
});

if (values.help) {
  printHelp();
  process.exit(0);
}

if (!values.url) {
  console.error('Error: --url is required\n');
  printHelp();
  process.exit(1);
}

// ─── Connect + discover ───────────────────────────────────────────────────────

const url = values.url;
const outFile = values.out!;

console.log(`Connecting to ${url} …`);

const mcpClient = new Client({ name: 'mcp-generate-types', version: '1.0.0' }, {});

try {
  // Try StreamableHTTP first, fall back to SSE — same logic as MCPClient
  try {
    const transport = await createTransport(url);
    await mcpClient.connect(transport);
  } catch {
    console.log('StreamableHTTP failed, trying SSE …');
    const transport = createSSETransport(url);
    await mcpClient.connect(transport);
  }
} catch (err) {
  console.error(`Could not connect to ${url}`);
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}

const { tools } = await mcpClient.listTools();
await mcpClient.close();

console.log(`Found ${tools.length} tools. Generating types …`);

// ─── Code generation ──────────────────────────────────────────────────────────

/** kebab-case or snake_case → PascalCase */
function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const lines: string[] = [
  `// Auto-generated by @stellar-mcp/client — DO NOT EDIT`,
  `// Source : ${url}`,
  `// Refresh: npx mcp-generate-types --url ${url} --out ${outFile}`,
  ``,
  `import { MCPClient, type MCPClientOptions } from '@stellar-mcp/client';`,
  ``,
  `// ─── Input Types ─────────────────────────────────────────────────────────────`,
  ``,
];

// Map of tool name → generated arg type name
const argTypeNames: Record<string, string> = {};

for (const tool of tools) {
  const typeName = `${toPascalCase(tool.name)}Args`;
  argTypeNames[tool.name] = typeName;

  const schema = tool.inputSchema as Record<string, unknown>;
  const hasProperties =
    schema.properties != null && Object.keys(schema.properties as object).length > 0;

  if (!hasProperties) {
    // No-arg tool — emit a clean empty type rather than { [k: string]: unknown }
    lines.push(`/** Args for \`${tool.name}\` — this tool takes no arguments. */`);
    lines.push(`export type ${typeName} = Record<string, never>;`);
    lines.push(``);
  } else {
    // Has args — compile JSON Schema → TypeScript interface
    const compiled = await compile(schema as Parameters<typeof compile>[0], typeName, {
      bannerComment: '',
      additionalProperties: false,
      unknownAny: false,
    });
    lines.push(compiled);
  }
}

// ─── Result Types ─────────────────────────────────────────────────────────────

lines.push(`// ─── Result Types ────────────────────────────────────────────────────────────`);
lines.push(``);

// Map of tool name → generated result type name (or 'unknown' when no outputSchema)
const resultTypeNames: Record<string, string> = {};

for (const tool of tools) {
  const typeName = `${toPascalCase(tool.name)}Result`;
  const outputSchema = tool.outputSchema as Record<string, unknown> | undefined;

  const hasOutputSchema =
    outputSchema != null &&
    outputSchema.properties != null &&
    Object.keys(outputSchema.properties as object).length > 0;

  if (hasOutputSchema) {
    resultTypeNames[tool.name] = typeName;
    const compiled = await compile(outputSchema as Parameters<typeof compile>[0], typeName, {
      bannerComment: '',
      additionalProperties: false,
      unknownAny: false,
    });
    lines.push(compiled);
  } else {
    resultTypeNames[tool.name] = 'unknown';
  }
}

// ─── ServerTools map ──────────────────────────────────────────────────────────

lines.push(`// ─── Tool Map ────────────────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`interface ServerTools {`);
for (const tool of tools) {
  lines.push(`  /** ${tool.description?.split('\n')[0] ?? tool.name} */`);
  lines.push(`  '${tool.name}': { args: ${argTypeNames[tool.name]}; result: ${resultTypeNames[tool.name]} };`);
}
lines.push(`}`);
lines.push(``);

// ─── createMCPClient factory ──────────────────────────────────────────────────

lines.push(`// ─── Typed Client Factory ────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`/**`);
lines.push(` * Create a fully typed MCP client for this server.`);
lines.push(` *`);
lines.push(` * Tool names are autocompleted and args are type-checked.`);
lines.push(` * Regenerate this file with \`npx mcp-generate-types\` if the server changes.`);
lines.push(` *`);
lines.push(` * @example`);
lines.push(` * \`\`\`ts`);
lines.push(` * import { createMCPClient } from './mcp-types';`);
lines.push(` *`);
lines.push(` * const client = createMCPClient({`);
lines.push(` *   url: '${url}',`);
lines.push(` *   networkPassphrase: 'Test SDF Network ; September 2015',`);
lines.push(` *   rpcUrl: 'https://soroban-testnet.stellar.org',`);
lines.push(` * });`);
lines.push(` *`);
lines.push(` * const { data } = await client.call('${tools[0]?.name ?? 'tool-name'}');`);
lines.push(` * \`\`\``);
lines.push(` */`);
lines.push(`export function createMCPClient(options: MCPClientOptions): MCPClient<ServerTools> {`);
lines.push(`  return new MCPClient<ServerTools>(options);`);
lines.push(`}`);
lines.push(``);

// ─── Write file ───────────────────────────────────────────────────────────────

const outPath = resolve(process.cwd(), outFile);
writeFileSync(outPath, lines.join('\n'), 'utf-8');

console.log(`\n✓ Written to ${outPath}`);
console.log(`  ${tools.length} tools typed\n`);
console.log(`Next steps:`);
console.log(`  import { createMCPClient } from './${outFile.replace(/\.ts$/, '')}';`);
console.log(`  const client = createMCPClient({ url, networkPassphrase, rpcUrl });`);
console.log(`  await client.call('...')  // fully typed\n`);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function printHelp(): void {
  console.log(`
mcp-generate-types — generate a typed client from a running MCP server

Usage:
  npx mcp-generate-types --url <mcp-url> [--out <file>]

Options:
  --url   MCP server URL (required), e.g. http://localhost:3001/mcp
  --out   Output file path (default: mcp-types.ts)
  --help  Show this help

Example:
  npx mcp-generate-types --url http://localhost:3001/mcp --out ./src/mcp-types.ts
`);
}
